export const cqcGuidance = {
  personalProfile: {
    title: "Personal Profile & Life History",
    why: "Understanding a resident's life history, career, family, and preferences establishes a baseline for person-centred care, ensuring they are treated as individuals and their identity is preserved.",
    how: "Conduct open-ended, non-intrusive interviews with the resident and next-of-kin, cross-referencing past hobbies, occupation details, and social histories in a quiet environment.",
    good: "Recording that Margaret was a secondary school teacher who loves classical piano and dislikes early mornings, allowing carers to converse about topics that interest her.",
    poor: "Leaving profile details blank or writing generic statements such as 'Resident is cooperative and likes TV.'",
    when: "Escalate when the resident displays signs of depression, withdrawal, or when memory decline prevents them from sharing their preferences.",
    who: "Inform the Activities Coordinator, Registered Manager, and family members to enrich the profile.",
    record: "Record life history milestones, preferred names, religion, key contacts, and likes/dislikes in the electronic profile.",
    dignity: "Validates the resident's achievements and identity, ensuring they are not referred to by room number or medical diagnosis.",
    success: "Resident actively engages in conversation about their favourite topics and shows signs of positive mood.",
    evidence: "A completed life history folder and evidence of staff tailoring conversations and activities to the resident's documented interests.",
    say: "Good morning Margaret, I heard you used to teach music. What was your favourite piece to play?",
    notSay: "Time for your wash, Room 4."
  },
  communication: {
    title: "Communication",
    why: "Effective communication is fundamental to choice and consent. Unmanaged communication barriers cause isolation, frustration, and challenging behaviours.",
    how: "Ensure hearing aids are clean and batteries working. Face the resident directly, maintain eye contact, speak clearly without shouting, and use visual prompts or translation cards if necessary.",
    good: "Carers check hearing aid battery status every morning, face the resident at eye level, and use short, clear sentences.",
    poor: "Speaking about the resident in their presence to other staff, or shouting at a resident who has a hearing aid.",
    when: "Escalate if there is a sudden change in hearing or speech, or if the resident begins withdrawing from conversations.",
    who: "Inform the GP, Audiologist, Speech and Language Therapist (SALT), and Care Team Leader.",
    record: "Record sensory aid status (cleaned, inserted), response latency, preferred communication style, and any signs of distress.",
    dignity: "Empowers the resident to voice their needs, express choices, and retain control over their daily routines.",
    success: "Resident responds to verbal/non-verbal cues and actively participates in daily decisions.",
    evidence: "Audits of hearing aid maintenance logs and observations of staff using appropriate non-verbal aids.",
    say: "Would you like tea or coffee today, Arthur? (pointing to cups)",
    notSay: "He doesn't understand anyway, just give him tea."
  },
  mobility: {
    title: "Mobility",
    why: "Safe mobility support maintains muscle function and independence while preventing catastrophic falls and fractures.",
    how: "Always consult the physiotherapy assessment. Inspect walking frames and hoists before use. Use double-staff support for hoists (e.g. LOLER checked). Ensure non-slip footwear is worn.",
    good: "Encouraging a resident to walk to the dining room using their Zimmer frame with one-to-one standby supervision, preserving gait.",
    poor: "Using a wheelchair for staff speed when the resident is fully capable of walking safely with their frame.",
    when: "Escalate if the resident reports joint pain, shows a sudden change in gait, or exhibits increased instability.",
    who: "Inform the Physiotherapist, Occupational Therapist (OT), and Care Team Leader.",
    record: "Record mobility aid used, distance walked, level of support required, and any verbal complaints of pain.",
    dignity: "Promotes physical independence, self-esteem, and social inclusion by enabling movement.",
    success: "Resident maintains their baseline mobility level without falls or fear of falling.",
    evidence: "Up-to-date OT assessments, hoist sling inspection tags, and logs matching scheduled mobilisations.",
    say: "Take your time, Margaret. I am right beside you. Place your hands on the walker.",
    notSay: "Hurry up, we have to get to the dining room now."
  },
  fallsRisk: {
    title: "Falls Risk",
    why: "Falls are a primary cause of physical deterioration and hospital admission in care settings. Managing risks protects the resident's physical integrity.",
    how: "Keep corridors clear. Ensure call bells are within reach. Monitor sensor mat activation. Check that falls risk assessments (e.g. FRAT) are reviewed monthly.",
    good: "Maintaining a clutter-free room, placing a sensor mat by the bed for a resident with advanced dementia, and checking non-slip socks are on.",
    poor: "Leaving the bed at high height, or failing to respond immediately to a sensor mat alarm.",
    when: "Escalate after any fall (completed incident log), or if falls frequency increases.",
    who: "Inform the GP, Falls Prevention Team, Registered Manager, and Next of Kin.",
    record: "Record post-fall checks (neuro observations), environmental audits, sensor mat function, and mobility adjustments.",
    dignity: "Allows safe risk-taking (e.g. moving around) with unobtrusive safety measures (e.g. low-profile beds).",
    success: "Reduction in falls frequency and resident maintains confidence in walking.",
    evidence: "FRAT assessments, post-falls review records, and evidence of corrective environmental actions.",
    say: "Let me adjust this table so you have a clear path to the bathroom, John.",
    notSay: "You fall too much, just stay in your chair."
  },
  personalCare: {
    title: "Personal Care & Hygiene",
    why: "Personal hygiene directly impacts skin health, physical comfort, self-respect, and prevention of urinary tract infections (UTIs).",
    how: "Prepare a warm room, explain each step before starting, respect preferred genders of carers, use warm water and resident's preferred toiletries.",
    good: "Asking the resident if they want a bath or shower, explaining every action before touching them, and ensuring they are covered at all times.",
    poor: "Giving a resident a quick bed-bath when they requested a bath, or washing a resident without explaining what is happening.",
    when: "Escalate if skin breaks down, if there is severe pain during care, or if resident repeatedly refuses care.",
    who: "Inform the District Nurse, Care Team Leader, and Registered Manager.",
    record: "Record wash type (bath, shower, bed wash), skin integrity status, toiletries used, and consent details.",
    dignity: "Protects bodily modesty, supports self-image, and honors personal choices about hygiene.",
    success: "Resident feels clean, smells fresh, and reports satisfaction with their hygiene routine.",
    evidence: "Complete bathing logs, skin inspection charts, and resident satisfaction survey feedback.",
    say: "Would you like me to wash your back now, Margaret? The water is warm.",
    notSay: "We have to wash you now, you haven't had a bath this week."
  },
  continence: {
    title: "Continence",
    why: "Poor continence management leads to skin maceration, pressure ulcers, UTIs, and extreme embarrassment.",
    how: "Implement a personalised toileting regime. Use correct sized continence pads. Clean from front to back to prevent infection. Apply barrier creams as directed.",
    good: "Discreetly asking a resident if they would like to use the toilet every 2 hours, maintaining privacy and skin health.",
    poor: "Leaving a resident in a wet continence pad for extended periods, or referring to pads as 'diapers' or 'nappies'.",
    when: "Escalate if urine is foul-smelling/dark, if bowel habits change suddenly, or if skin redness appears in the groin.",
    who: "Inform the Continence Nurse Advisor, GP, and Care Team Leader.",
    record: "Record pad changes, fluid output, bowel motions using the Bristol Stool Chart, and skin observations.",
    dignity: "Prevents public accidents, respects privacy, and ensures comfort and clean skin.",
    success: "No skin breakdown in the perineal area, and resident experiences zero continence accidents.",
    evidence: "Completed bowel charts, continence assessments, and fluid balance records.",
    say: "Shall we walk to the bathroom now and make sure you're comfortable, Arthur?",
    notSay: "Your pad is wet again, we need to change you."
  },
  nutrition: {
    title: "Nutrition & Hydration",
    why: "Malnutrition and dehydration cause renal failure, urinary infections, confusion, and muscle wasting.",
    how: "Monitor food consistency (e.g. IDDSI levels for choking risks). Record fluid intake in milliliters (ml). Provide adaptive cutlery. Sit next to the resident at eye level.",
    good: "Providing pureed food in a visually appealing separate format, offering a choice of drinks, and documenting fluid intake immediately.",
    poor: "Mixing pureed food items together, or leaving a hot drink out of a resident's reach.",
    when: "Escalate if fluid intake falls below 1000ml in 24 hours, or if weight drops by >5% month-on-month.",
    who: "Inform the Dietitian, SALT Team, GP, and Registered Manager.",
    record: "Record percentage of food eaten, fluid volume in ml, weight logs, and swallowing issues.",
    dignity: "Honours cultural and dietary preferences, supports independence during eating, and prevents malnutrition.",
    success: "Stable weight logs, normal hydration status, and positive dining feedback.",
    evidence: "Fluid charts, MUST screening forms, weight charts, and SALT guidelines followed at meals.",
    say: "Here is your beef and potatoes, Margaret, served separately. Which would you like to try first?",
    notSay: "Open up, eat this mash."
  },
  medication: {
    title: "Medication Management",
    why: "Medication errors can be fatal. Proper administration manages symptoms, maintains health, and controls pain safely.",
    how: "Follow the 6 rights of administration. Check MAR charts carefully. Verify double-signatures for controlled drugs. Ensure no covert administration unless authorized under MCA/DoLS.",
    good: "Confirming identity, explaining the medication's purpose, offering water, and signing the MAR chart only after witnessing ingestion.",
    poor: "Leaving pills on a resident's table for them to take later, or signing the MAR chart before they take the pills.",
    when: "Escalate immediately if a medication is refused, if there is a medication error, or if side effects occur.",
    who: "Inform the GP, Lead Pharmacist, Registered Manager, and Care Team Leader.",
    record: "Record MAR chart compliance, controlled drug registers, side effects, and refusal reasons.",
    dignity: "Maintains resident control over their body and respects their right to refuse medication with proper clinical follow-up.",
    success: "Zero medication administration errors and optimal symptom/pain management.",
    evidence: "Fully completed MAR sheets, fridge temperature logs, and medication audits.",
    say: "Here is your morning tablet for your joints, Arthur. Would you like a sip of water first?",
    notSay: "Just swallow this."
  },
  skinIntegrity: {
    title: "Skin Integrity & Pressure Care",
    why: "Pressure ulcers are highly painful, prone to infection, and represent a serious safeguarding failure.",
    how: "Use the Waterlow scale. Ensure regular repositioning (e.g. 2-hourly). Check pressure relief mattresses are plugged in and set to correct weight. Avoid shearing during transfers.",
    good: "Staff assist a high-risk resident to turn every 2 hours, inspecting pressure points and documenting in a turning chart.",
    poor: "Failing to turn a resident on a pressure relief schedule, or dragging a resident up in bed causing skin tears.",
    when: "Escalate if skin redness does not blanch (turn white) when pressed, or if skin breaks open.",
    who: "Inform the Tissue Viability Nurse (TVN), District Nurse, and Registered Manager.",
    record: "Record turning logs, Waterlow score, skin conditions, and barrier cream application.",
    dignity: "Ensures freedom from physical pain, maintains skin comfort, and provides non-intrusive safety.",
    success: "Complete prevention of pressure ulcers and healthy skin integrity.",
    evidence: "Repositioning charts, TVN treatment plans, and mattress safety checks.",
    say: "I am going to help you roll onto your left side now, John, to keep your hips comfortable.",
    notSay: "You have to stay on your back, I don't have time to turn you."
  },
  mentalHealth: {
    title: "Mental Health & Wellbeing",
    why: "Depression, anxiety, and social isolation are prevalent in care environments. Supporting mental health is critical for overall wellbeing.",
    how: "Establish therapeutic relationships, encourage active listening, support engagement in activities, and facilitate connections with families.",
    good: "Spending 15 minutes of quiet time with a resident who is feeling anxious, listening to their worries without dismissing them.",
    poor: "Ignoring a resident's low mood or attributing withdrawal entirely to 'old age.'",
    when: "Escalate if the resident expresses suicidal thoughts, or shows prolonged withdrawal or refusal to eat.",
    who: "Inform the GP, Community Mental Health Team (CMHT), and Registered Manager.",
    record: "Record mood indicators, social engagement levels, family visits, and therapy compliance.",
    dignity: "Values the resident's emotional state, respects their feelings, and promotes mental self-worth.",
    success: "Resident reports feeling happy, secure, and actively participates in community life.",
    evidence: "Completed social interaction logs, depression screening tools, and mental health review records.",
    say: "I noticed you seem a bit quiet today, Margaret. Would you like to sit and talk for a moment?",
    notSay: "Stop crying, you have a nice room here."
  },
  dementiaCare: {
    title: "Dementia Care",
    why: "Dementia affects orientation, memory, and reasoning. Specialized care prevents distress, escalations, and preserves dignity.",
    how: "Use Validation Therapy rather than arguing. Maintain a calm environment, reduce noise, use visual cues, and establish a strict daily routine.",
    good: "When a resident asks for their deceased mother, staff validate the emotion: 'Tell me about your mother, she sounds lovely,' instead of arguing that she is dead.",
    poor: "Arguing with a confused resident, or locking them in a room to prevent wandering.",
    when: "Escalate if confusion increases suddenly (indicates possible UTI), or if aggression occurs.",
    who: "Inform the GP, Dementia Care Specialist Nurse, and Care Team Leader.",
    record: "Record sundowning patterns, triggers of distress, de-escalation strategies, and ABC charts.",
    dignity: "Minimizes fear and confusion, values the resident's reality, and builds trust.",
    success: "Resident is calm, oriented to their emotional state, and distress incidents are minimized.",
    evidence: "Dementia-specific care plans, validation therapy logs, and behavior charts.",
    say: "It sounds like you miss your home, Arthur. Tell me about the garden you had there.",
    notSay: "Your house was sold years ago. You live here now."
  },
  activities: {
    title: "Activities & Social Needs",
    why: "Meaningful occupation prevents depression, maintains cognitive function, and promotes physical mobility.",
    how: "Tailor activities to life history. Offer 1:1 sessions for bed-bound residents. Support group participation. Respect the right to choose isolation if preferred.",
    good: "Providing a resident who was a carpenter with wooden blocks and sandpaper to work with, fostering a sense of purpose.",
    poor: "Placing a resident in front of a television all day without personal interaction.",
    when: "Escalate if the resident shows signs of extreme boredom, apathy, or refuses to participate in any activity.",
    who: "Inform the Activities Coordinator, Care Team Leader, and family members.",
    record: "Record activity duration, engagement level, social responses, and 1:1 time details.",
    dignity: "Validates personal purpose, keeps the mind active, and ensures the resident leads a fulfilling life.",
    success: "Resident shows high participation rates, positive feedback, and active engagement.",
    evidence: "Activities logs, photo evidence of events, and resident surveys.",
    say: "Would you like to join the gardening club this afternoon, John? We are planting tomatoes.",
    notSay: "Sit here and watch this show."
  },
  sleep: {
    title: "Sleep & Night Needs",
    why: "Poor sleep affects cognitive function, increases falls risk, and leads to daytime fatigue and irritability.",
    how: "Ensure a quiet environment. Keep doors closed quietly. Check safety parameters (sensor mats). Avoid waking residents unnecessarily for checks.",
    good: "Using low-intensity lighting during night checks and keeping noise to a minimum, preserving sleep cycles.",
    poor: "Turning on bright overhead bedroom lights during a routine check, waking the resident.",
    when: "Escalate if night-time confusion/sundowning increases, or if severe insomnia persists.",
    who: "Inform the GP, Care Team Leader, and Night Staff Lead.",
    record: "Record sleep duration, night check outcomes, hydration offered at night, and repositioning details.",
    dignity: "Ensures rest, comfort, and physical privacy in their own bedroom overnight.",
    success: "Resident reports feeling rested and night disturbances are reduced.",
    evidence: "Night check sheets, sleep calendars, and reviews of medication (sedative check).",
    say: "I am just going to adjust your blanket to make sure you are warm, Margaret. Sleep well.",
    notSay: "Wake up, I need to check your pad."
  },
  healthConditions: {
    title: "Health Conditions & Clinical Needs",
    why: "Unmanaged clinical conditions (like diabetes, arthritis, COPD) cause rapid physical deterioration and pain.",
    how: "Administer clinical checks (blood pressure, blood glucose) as scheduled. Follow specialist guidelines. Monitor symptoms closely.",
    good: "Checking blood glucose levels precisely at 8 AM as per diabetes care plan, maintaining stable parameters.",
    poor: "Failing to check blood glucose, or ignoring breathing difficulties in a COPD resident.",
    when: "Escalate immediately if vital signs deviate from safe limits, or if acute symptoms appear.",
    who: "Inform the GP, Lead Nurse, Emergency Services (999 if necessary), and Registered Manager.",
    record: "Record blood pressure, heart rate, blood glucose, oxygen saturation, and clinical interventions.",
    dignity: "Preserves physical stability, reduces pain, and ensures the resident remains comfortable and safe.",
    success: "Clinical conditions remain stable and managed, with minimal emergency admissions.",
    evidence: "Clinical observation logs, diabetic charts, GP communication sheets.",
    say: "I am going to check your blood sugar now, John. Just a quick tap on your finger.",
    notSay: "Hold still, I have to prick you."
  },
  endOfLife: {
    title: "End of Life (MCA/DoLS)",
    why: "End-of-life care must be compassionate, pain-free, and respect the resident's spiritual and final wishes.",
    how: "Verify active DNACPR status. Review advance care directives. Administer pain relief (syringes). Respect religious and funeral wishes.",
    good: "Ensuring a quiet, calm room with soft music, administering pain relief as scheduled, and supporting family members at the bedside.",
    poor: "Failing to verify DNACPR status and performing CPR against the resident's legal directives.",
    when: "Escalate if pain management is ineffective, or if the resident enters active dying phase.",
    who: "Inform the GP, Palliative Care Team, Family, and Registered Manager.",
    record: "Record pain audits, hydration checks, mouth care frequency, and family support notes.",
    dignity: "Ensures a peaceful, respectful death, honoring advance directives and personal beliefs.",
    success: "Resident remains pain-free, comfortable, and dies in peace with family present.",
    evidence: "Signed DNACPR forms, Advance Decisions to Refuse Treatment (ADRT), and palliative logs.",
    say: "We are here with you, Margaret. You are safe. I will make sure you are comfortable.",
    notSay: "She is not going to make it anyway."
  }
};
