export const personalTemplates = {
  morningRoutine: {
    title: "Morning Routine",
    why: "Ensures the resident starts their day in a positive, familiar manner, respecting their sleep-wake cycles and personal preferences.",
    how: "Approach the resident between 07:30 and 08:30. Speak softly, open curtains slowly, and offer a morning cup of tea before assistance.",
    good: "Resident wakes naturally, has a warm drink in bed, and chooses their own clothes for the day.",
    poor: "Waking the resident abruptly, forcing them to get up early, or not offering a choice of clothing.",
    when: "Escalate if the resident is consistently lethargic, refuses to wake, or shows signs of morning disorientation.",
    who: "Inform the Duty Nurse, Care Team Leader, and Activities Coordinator.",
    record: "Record time of waking, mood, response to waking, and choice of clothing.",
    dignity: "Honours the resident's independence by letting them dictate their morning schedule.",
    success: "Resident is smiling, dressed in their chosen clothes, and seated comfortably for breakfast.",
    evidence: "Daily logs showing variable wake times matching preferences, and resident feedback."
  },
  eveningRoutine: {
    title: "Evening Routine",
    why: "Supports natural circadian rhythms and reduces night-time distress or wandering behaviors.",
    how: "Assist with wind-down from 20:00. Offer warm milk or chamomile tea, adjust lighting, and assist with nightwear.",
    good: "Resident is relaxed, listening to quiet music, and settles into bed at their preferred time.",
    poor: "Forcing a rigid bedtime, leaving lights bright, or skipping wind-down conversations.",
    when: "Escalate if resident shows high anxiety (sundowning) or repeatedly refuses to settle.",
    who: "Inform the Night Care Staff, Team Leader, and GP if sleep issues persist.",
    record: "Record settling time, nightwear worn, fluid intake, and sleep quality.",
    dignity: "Respects the resident's right to choose when they go to sleep and how they prepare for bed.",
    success: "Resident sleeps peacefully through the night with minimal interruptions.",
    evidence: "Night checks showing peaceful sleep patterns and consistent evening routines."
  },
  bathing: {
    title: "Bathing & Showering",
    why: "Maintains skin cleanliness, prevents infections, and provides comfort and relaxation.",
    how: "Check water temperature (must be between 38°C and 41°C). Maintain privacy with towels, and explain each washing step.",
    good: "Resident enjoys a warm bath twice weekly, listening to preferred radio station, with full privacy maintained.",
    poor: "Washing the resident in a cold room, not checking water temperature, or leaving them uncovered.",
    when: "Escalate if resident shows pain during transfers or if skin redness is observed.",
    who: "Inform the Physiotherapist (for hoist reviews) and the Lead Nurse.",
    record: "Record date/time of bath, skin checks, resident's response, and toiletries used.",
    dignity: "Protects bodily modesty by keeping towels over unwashed areas during care.",
    success: "Resident expresses feeling refreshed and shows no signs of skin irritation.",
    evidence: "Bathing log sheets showing completed schedule and skin integrity checks."
  },
  washing: {
    title: "Washing & Daily Hygiene",
    why: "Maintains daily hygiene and freshness between full baths or showers.",
    how: "Use warm water and a clean washcloth. Offer choices for face, hands, and personal hygiene washes.",
    good: "Carer supports resident to wash their own face and hands, promoting reablement.",
    poor: "Carer washing the resident without letting them try to do it themselves.",
    when: "Escalate if skin irritation, rashes, or pressure marks are spotted.",
    who: "Inform the Care Team Leader and Wound Care Nurse.",
    record: "Record wash completed, skin condition, and level of assistance needed.",
    dignity: "Promotes self-esteem by encouraging self-washing where possible.",
    success: "Resident is clean, comfortable, and has participated in their daily hygiene.",
    evidence: "Daily care notes documenting self-care level and skin checks."
  },
  hairCare: {
    title: "Hair Care & Styling",
    why: "Directly impacts personal identity, self-image, and dignity.",
    how: "Wash hair weekly with resident's preferred shampoo. Style as per their lifelong preference.",
    good: "Resident visits the in-house salon weekly; hair is styled in her signature roller curls.",
    poor: "Leaving hair unbrushed, messy, or using generic products without choice.",
    when: "Escalate if scalp issues, dandruff, or hair loss are noted.",
    who: "Inform the Hairdresser, GP, and Next of Kin.",
    record: "Record weekly washes, styling choices, and scalp condition.",
    dignity: "Preserves the resident's personal style and pride in their appearance.",
    success: "Resident expresses pride in their hair and smiles when looking in the mirror.",
    evidence: "Hair care logs, hairdresser visit notes, and resident photographs."
  },
  oralCare: {
    title: "Oral Care",
    why: "Prevents gum disease, tooth decay, pain, and systemic infections like aspiration pneumonia.",
    how: "Assist with soft-bristled brush and fluoride toothpaste twice daily. Keep mouth moist.",
    good: "Teeth are brushed thoroughly morning and night, followed by a gentle alcohol-free mouthwash.",
    poor: "Neglecting oral care, or brushing aggressively causing bleeding gums.",
    when: "Escalate if resident reports mouth pain, bleeding gums, or has white patches in mouth.",
    who: "Inform the Dentist, Nurse, and Care Team Leader.",
    record: "Record frequency of brushing, mouth observations, and any pain reported.",
    dignity: "Ensures fresh breath and physical comfort during social interactions.",
    success: "Resident is pain-free, mouth is clean, and breath is fresh.",
    evidence: "Daily oral care logs and dentist review sheets."
  },
  dentures: {
    title: "Dentures Care",
    why: "Ensures resident can chew food safely and speak clearly.",
    how: "Clean dentures twice daily using denture cream. Soak in water overnight in a labeled container.",
    good: "Dentures are cleaned, soaked overnight, and correctly fitted in the morning.",
    poor: "Leaving dentures in overnight, or using boiling water which warps them.",
    when: "Escalate if dentures are loose, cracked, or causing mouth sores.",
    who: "Inform the Dentist and Care Team Leader.",
    record: "Record denture cleaning, fitting status, and oral tissue condition.",
    dignity: "Restores natural smile and speech clarity, avoiding embarrassment.",
    success: "Resident eats their meal comfortably with dentures fitted.",
    evidence: "Denture care logs and dental inspection records."
  },
  shaving: {
    title: "Shaving & Grooming",
    why: "Maintains personal grooming standards and preserves male or female preferences.",
    how: "Use clean razor and shaving foam for wet shaves, or electric shaver. Apply aftershave if liked.",
    good: "Resident receives a careful shave every morning, using their preferred scented balm.",
    poor: "Shaving without lather, causing razor burns, or leaving stray facial hairs.",
    when: "Escalate if skin is cut, showing razor rash, or if resident refuses shaving.",
    who: "Inform the Care Team Leader and GP if rash is persistent.",
    record: "Record shave completed, skin response, and resident's preferences.",
    dignity: "Ensures a neat, clean appearance that respects the resident's life-long routine.",
    success: "Resident touches his smooth face and expresses satisfaction.",
    evidence: "Daily grooming checklist and resident feedback."
  },
  skinInspection: {
    title: "Skin Inspection",
    why: "Prevents pressure ulcer development by catching early signs of redness (non-blanching erythema).",
    how: "Inspect pressure points (heels, sacrum, elbows) twice daily during dressing.",
    good: "Checking skin integrity discreetly, applying barrier creams, and noting no redness.",
    poor: "Assuming skin is fine without visual checks, leading to deep pressure wounds.",
    when: "Escalate immediately if non-blanching redness, broken skin, or blisters are seen.",
    who: "Inform the Duty Nurse, GP, and Wound Specialist Nurse.",
    record: "Record skin inspection results, Waterlow score updates, and cream applications.",
    dignity: "Protects physical health in a private, respectful manner during routine checks.",
    success: "Skin remains intact with no pressure damage or dry areas.",
    evidence: "Skin bundles, Waterlow assessment charts, and repositioning logs."
  },
  nailCare: {
    title: "Nail Care",
    why: "Prevents self-scratching, ingrown nails, and local infections.",
    how: "File fingernails weekly. Do NOT cut toenails of diabetic residents (podiatry only).",
    good: "Nails are filed smoothly and kept clean; resident receives a relaxing hand massage.",
    poor: "Cutting nails too short, causing bleeding, or ignoring dirty fingernails.",
    when: "Escalate if nails are thickened, discoloured (fungal), or showing signs of infection.",
    who: "Inform the Chiropodist/Podiatrist and Care Team Leader.",
    record: "Record nail cleaning, filing, and any podiatry referrals.",
    dignity: "Ensures clean, presentable hands that the resident is happy to show.",
    success: "Nails are smooth, clean, and resident is comfortable.",
    evidence: "Nail care logs and podiatry scheduling sheets."
  },
  dressing: {
    title: "Dressing & Clothing",
    why: "Directly influences personal choice, identity, and protection from cold.",
    how: "Lay out choices. Assist with dressing while encouraging independent movement.",
    good: "Resident chooses a matching blouse and skirt, assists with sleeves, and looks smart.",
    poor: "Dressing the resident in mismatched clothes, or not letting them choose.",
    when: "Escalate if dressing causes joint pain, or if clothing is consistently too tight/loose.",
    who: "Inform the Occupational Therapist and Next of Kin (for clothing sizes).",
    record: "Record level of help, clothes chosen, and physical tolerance.",
    dignity: "Ensures the resident looks presentable and maintains their personal style.",
    success: "Resident is dressed comfortably and smartly in their preferred clothing.",
    evidence: "Dressing checklists and daily care records."
  },
  jewellery: {
    title: "Jewellery & Make-up",
    why: "Preserves self-expression, femininity/masculinity, and connection to past life.",
    how: "Assist resident to apply their signature lipstick and wear their wedding ring safely.",
    good: "Resident wears her pearl necklace and light blush daily, boosting her self-confidence.",
    poor: "Leaving jewelry locked away without offering, or ignoring makeup preferences.",
    when: "Escalate if jewelry becomes too tight (causing skin cuts) or is lost.",
    who: "Inform the Care Team Leader, Next of Kin, and Administrator (valuable inventory).",
    record: "Record jewelry worn, makeup applied, and safe storage logs.",
    dignity: "Celebrates the resident's individuality and aesthetic preferences.",
    success: "Resident smiles and feels attractive in their chosen accessories.",
    evidence: "Jewellery registry checks and client satisfaction records."
  },
  continence: {
    title: "Continence",
    why: "Avoids discomfort, skin maceration, UTIs, and public embarrassment.",
    how: "Assess pad capacity, change 4-hourly or when wet. Clean skin and apply barrier cream.",
    good: "Discreet pad checks, using correct size, and keeping resident fresh and clean.",
    poor: "Leaving a resident in a wet pad for hours, or neglecting perineal wash.",
    when: "Escalate if skin breakdown, rash, or changes in urine color are found.",
    who: "Inform the GP, Continence Nurse, and Care Team Leader.",
    record: "Record pad changes, skin checks, and Bristol Stool logs.",
    dignity: "Respects modesty by changing pads in private and maintaining clean skin.",
    success: "No perineal redness, and zero leakage accidents.",
    evidence: "Completed bowel charts, pad logs, and skin checks."
  },
  feminineCare: {
    title: "Feminine Care",
    why: "Supports female-specific hygiene, preventing infections and odor.",
    how: "Provide warm wash water. Wash from front to back using gentle wipes.",
    good: "Assisting resident with daily feminine wash with utmost privacy and female staff preference.",
    poor: "Ignoring specific hygiene needs or using heavily scented soaps.",
    when: "Escalate if unusual discharge, blood, or localized pain is reported.",
    who: "Inform the Lead Nurse, GP, and female carer team.",
    record: "Record hygiene completed, skin state, and any concerns.",
    dignity: "Protects personal hygiene in a private and sensitive manner.",
    success: "Resident is clean, odorless, and free from infections.",
    evidence: "Feminine care logs and nurse reports."
  },
  toileting: {
    title: "Toileting",
    why: "Promotes bladder health and prevents falls caused by unassisted attempts to toilet.",
    how: "Offer toilet prompts every 2 hours. Support transfers with grab rails or stand-aid.",
    good: "Prompting resident before meals, ensuring grab rails are utilized, and allowing privacy.",
    poor: "Telling resident to 'just use the pad' instead of helping them to the toilet.",
    when: "Escalate if frequency increases or if difficulty voiding is reported.",
    who: "Inform the GP and Continence Team.",
    record: "Record times of toilets, successful voids, and assistance level.",
    dignity: "Encourages normal toilet habits rather than relying on incontinence aids.",
    success: "Resident toilets safely and retains maximum continence.",
    evidence: "Toilet charting sheets and falls audits."
  },
  privacy: {
    title: "Privacy & Dignity",
    why: "Legal requirement under CQC Regulation 10 to treat residents with respect and maintain privacy.",
    how: "Close doors and curtains. Knock before entering. Use towels to cover areas not being washed.",
    good: "Carer knocks, waits for answer, enters, and closes window blinds before starting care.",
    poor: "Entering a resident's room without knocking, or leaving doors open during wash.",
    when: "Escalate if staff are found breaching privacy guidelines.",
    who: "Inform the Registered Manager and Team Leader.",
    record: "Record compliance with privacy choices and consent verbal logs.",
    dignity: "Ensures the resident feels safe and respected in their private space.",
    success: "Resident expresses feeling secure and respected in their home.",
    evidence: "CQC observational audits, staff training logs, and resident feedback."
  },
  independence: {
    title: "Independence",
    why: "Maintains cognitive and physical function, slowing the progression of dependency.",
    how: "Encourage resident to wash, dress, and feed themselves as much as possible, assisting only when needed.",
    good: "Resident buttons their own shirt with carers providing standby encouragement.",
    poor: "Doing tasks for the resident to save time, reducing their abilities.",
    when: "Escalate if mobility or dexterity declines, needing formal OT review.",
    who: "Inform the Occupational Therapist and Care Planner.",
    record: "Record tasks completed independently and areas needing support.",
    dignity: "Promotes self-worth and control over one's life.",
    success: "Resident retains baseline functional abilities longer.",
    evidence: "Care plan audits showing active reablement goals and outcomes."
  },
  preferredCarers: {
    title: "Preferred Carers",
    why: "Respects cultural, religious, and personal choices regarding intimate care.",
    how: "Assign staff matching the resident's preference (e.g. female-only for personal care).",
    good: "The rota is adjusted so that female HCAs support Arthur with bathing, as requested.",
    poor: "Ignoring preferences and assigning male staff to a resident who requested female-only.",
    when: "Escalate if rota constraints prevent fulfilling preferences.",
    who: "Inform the Rota Coordinator and Registered Manager.",
    record: "Record carer preference in the care plan, and daily compliance logs.",
    dignity: "Reduces anxiety and respects personal boundaries.",
    success: "Resident feels comfortable and secure during intimate care.",
    evidence: "Rota audits and daily care log checks."
  },
  communication: {
    title: "Communication",
    why: "Fundamental to building relationships, obtaining consent, and reducing frustration.",
    how: "Use clear, slow speech. Ensure sensory aids (glasses, hearing aids) are in place and clean.",
    good: "Speaking directly at eye level, using visual cards, and checking hearing aid batteries daily.",
    poor: "Speaking about the resident in front of them, or shouting.",
    when: "Escalate if sudden speech or hearing changes occur.",
    who: "Inform the GP, Audiologist, and Speech Therapist.",
    record: "Record communication methods used, effectiveness, and aid checks.",
    dignity: "Enables the resident to express their needs and choices clearly.",
    success: "Resident actively participates in choices and expresses their mind.",
    evidence: "Communication assessment sheets and care notes."
  },
  positioning: {
    title: "Positioning",
    why: "Prevents pressure sores by redistributing body weight regularly.",
    how: "Turn resident every 2-4 hours in bed using slide sheets. Check skin pressure points.",
    good: "Following a 2-hourly turning chart, skin remains healthy and intact.",
    poor: "Leaving a resident in one position for long periods, leading to sores.",
    when: "Escalate immediately if skin redness does not fade after 15 minutes of off-loading.",
    who: "Inform the Duty Nurse, GP, and Wound Specialist.",
    record: "Record positioning log (left side, back, right side) and skin condition.",
    dignity: "Ensures physical comfort and safety in a gentle, caring manner.",
    success: "Zero skin breakdown or pressure damage.",
    evidence: "Turning charts, skin inspections, and mattress audits."
  },
  pain: {
    title: "Pain",
    why: "Untreated pain destroys quality of life, causes agitation, and limits mobility.",
    how: "Assess pain daily using Abbey Pain Scale (for non-verbal) or numeric scale. Administer PRN meds.",
    good: "Checking pain level before mobility, administering PRN Paracetamol, and noting relief.",
    poor: "Ignoring non-verbal signs of pain (grimacing, moaning) or delaying meds.",
    when: "Escalate if pain is uncontrolled by prescribed medication.",
    who: "Inform the GP, Palliative Care Team, and Duty Nurse.",
    record: "Record pain score, medication given, and effectiveness checks.",
    dignity: "Ensures the resident lives comfortably and pain-free.",
    success: "Resident reports being comfortable and displays relaxed body language.",
    evidence: "Abbey pain charts, MAR records, and post-medication notes."
  },
  equipment: {
    title: "Equipment",
    why: "Ensures mechanical and electrical aids are safe for resident and staff use.",
    how: "Inspect hoist slings, sensor mats, and profiling bed rails daily. Check service dates.",
    good: "Verifying the LOLER safety tag on the hoist sling is valid before transferring Arthur.",
    poor: "Using frayed slings or broken sensor mats, risking injury.",
    when: "Escalate if equipment is faulty, expired, or showing wear.",
    who: "Inform the Maintenance Officer and Registered Manager.",
    record: "Record daily equipment checks, faults, and maintenance logs.",
    dignity: "Guarantees a safe, secure care environment.",
    success: "Zero accidents related to equipment failure.",
    evidence: "LOLER certificate folders, hoist logs, and maintenance logs."
  },
  pressureChecks: {
    title: "Pressure Area Checks",
    why: "Detects early pressure damage before it degrades into open pressure ulcers.",
    how: "Visual check of heels, sacrum, and hips during washes. Update Waterlow risk score monthly.",
    good: "Documenting sacral check is clear; pressure-relieving air mattress pressure is correct.",
    poor: "Failing to check mattress settings or ignoring resident complaints of heel pain.",
    when: "Escalate if skin breakdown, blanching redness, or heat is found.",
    who: "Inform the Lead Nurse, GP, and Tissue Viability Nurse.",
    record: "Record Waterlow score, mattress settings, and skin status.",
    dignity: "Maintains skin integrity and keeps the resident comfortable.",
    success: "Resident has intact, healthy skin and correctly adjusted pressure aids.",
    evidence: "Monthly Waterlow charts, mattress checks, and nurse logs."
  },
  infectionControl: {
    title: "Infection Control",
    why: "Prevents the spread of infections (e.g. Norovirus, MRSA) in communal settings.",
    how: "Wear appropriate PPE (apron, gloves) for personal care. Dispose of soiled items immediately.",
    good: "Carer performs hand hygiene, wears fresh PPE for washing, and sanitizes surfaces.",
    poor: "Reusing aprons between residents, or failing to wash hands after care.",
    when: "Escalate if resident shows signs of infection (fever, cough, diarrhea).",
    who: "Inform the Duty Nurse, Infection Control Lead, and GP.",
    record: "Record PPE usage compliance, clinical waste logs, and sanitization checks.",
    dignity: "Ensures a clean, safe environment that respects resident health.",
    success: "No cross-infection or outbreak occurs in the home.",
    evidence: "Infection control audit sheets, PPE inventory, and training logs."
  },
  escalation: {
    title: "Escalation",
    why: "Ensures timely clinical intervention before conditions deteriorate dangerously.",
    how: "Recognize changes in baseline (e.g. confusion, fall, high temperature) and report immediately.",
    good: "Carer notices Arthur is confused, takes vitals, logs a NEWS2 score, and alerts the Nurse.",
    poor: "Ignoring subtle changes in behavior or delayed reporting of clinical vitals.",
    when: "Escalate immediately if NEWS2 score is 3 or higher, or if acute distress is observed.",
    who: "Inform the Duty Nurse, GP, and Care Manager.",
    record: "Record clinical vital logs, NEWS2 chart, time of alert, and response.",
    dignity: "Ensures rapid, professional medical response.",
    success: "Deteriorating conditions are managed before they become emergencies.",
    evidence: "NEWS2 charts, communication logs, and incident records."
  },
  review: {
    title: "Review",
    why: "Ensures the care plan remains up-to-date with the resident's evolving needs.",
    how: "Conduct formal reviews monthly or immediately after any significant clinical change.",
    good: "Collaborating with next-of-kin to review care preferences and update the profile.",
    poor: "Signing off reviews as 'no change' without actually reviewing preferences or health changes.",
    when: "Escalate if the care plan lacks details or if assessments are overdue.",
    who: "Inform the Care Planner, Registered Manager, and Resident/Family.",
    record: "Record review date, participants, changes made, and signatures.",
    dignity: "Supports resident-centered care by keeping preferences active and accurate.",
    success: "Care plan accurately mirrors the resident's current status and wishes.",
    evidence: "Monthly review logs, updated assessments, and auditor reports."
  },
  expectedOutcomes: {
    title: "Expected Outcomes",
    why: "Defines measurable goals for care, ensuring the support is effective.",
    how: "Set SMART (Specific, Measurable, Achievable, Realistic, Time-bound) targets with the resident.",
    good: "Aiming to maintain Margaret's mobility (walk 50m with walker) for the next 3 months.",
    poor: "Setting vague outcomes like 'Arthur should be kept happy and healthy.'",
    when: "Escalate if outcomes are consistently missed, indicating declining health.",
    who: "Inform the Registered Manager, MDT team, and Resident.",
    record: "Record progress updates against specific goals monthly.",
    dignity: "Focuses care on achievements, independence, and personal growth.",
    success: "Resident achieves their personalized care goals.",
    evidence: "Care goal tracking sheets and review notes."
  }
};

export const dementiaTemplates = {
  diagnosis: {
    title: "Diagnosis & Stage",
    why: "Provides understanding of the resident's cognitive capabilities and guides communication styles.",
    how: "Check medical files. Note if Alzheimer's, Vascular, or Mixed dementia, and the current stage (Mild/Moderate/Severe).",
    good: "Carer knows Arthur has moderate Alzheimer's, so they use short sentences and visual choices.",
    poor: "Treating a resident with severe dementia as if they have full cognitive capacity, causing distress.",
    when: "Escalate if sudden cognitive drop or acute confusion (delirium) occurs.",
    who: "Inform the GP, Psychiatric Lead, and Registered Manager.",
    record: "Record cognitive test scores (MMSE), diagnosis date, and clinical stage.",
    dignity: "Tailors support to the resident's cognitive level, avoiding frustration.",
    success: "Support matches cognitive baseline, maintaining calm interactions.",
    evidence: "GP diagnosis records and cognitive assessments."
  },
  memory: {
    title: "Memory",
    why: "Identifies short-term memory gaps and outlines memory-jogging aids.",
    how: "Place orientation calendar, labels on drawers, and photo booklets in the room.",
    good: "Resident uses labeled drawers to find clothes independently, boosting confidence.",
    poor: "Correcting memory errors constantly, causing embarrassment and distress.",
    when: "Escalate if memory issues lead to safety risks (e.g. eating non-food items).",
    who: "Inform the GP and Care Team Leader.",
    record: "Record memory aids checked, orientation level, and any memory-related distress.",
    dignity: "Avoids challenging memory errors, validating the resident's reality instead.",
    success: "Resident navigates their room and day with minimal confusion.",
    evidence: "Completed memory support logs and activity logs."
  },
  orientation: {
    title: "Orientation",
    why: "Reduces anxiety caused by not knowing the time, place, or season.",
    how: "Display large clock, daily schedule whiteboard, and discuss current season gently.",
    good: "Referencing the autumn leaves outside to orient the resident to the month.",
    poor: "Leaving resident without clocks or schedule guides, leaving them disoriented.",
    when: "Escalate if disorientation leads to exit-seeking or panic.",
    who: "Inform the Care Team Leader and family.",
    record: "Record orientation checks and response to orientation prompts.",
    dignity: "Validates feelings first before orienting, avoiding arguments.",
    success: "Resident feels safe and oriented in their surroundings.",
    evidence: "Environmental checks and orientation aids in room."
  },
  communication: {
    title: "Communication",
    why: "Enables connection and reduces behaviors of distress caused by misunderstood needs.",
    how: "Use validation therapy. Do not argue or correct. Face resident and speak calmly.",
    good: "Arthur says he wants to go to work. Carer says: 'Tell me about your job,' validation therapy.",
    poor: "Telling Arthur: 'You retired 20 years ago, you don't work,' causing agitation.",
    when: "Escalate if communication breaks down completely, causing aggression.",
    who: "Inform the SALT Team and Dementia Specialist.",
    record: "Record cues used, phrases that calm the resident, and non-verbal signs.",
    dignity: "Validates the resident's feelings and current reality, protecting self-worth.",
    success: "Resident feels understood and remains calm and cooperative.",
    evidence: "Communication plans, staff training, and review logs."
  },
  decisionMaking: {
    title: "Decision making",
    why: "Fulfills legal duty under Mental Capacity Act (MCA) 2005. Presumes capacity unless proven otherwise.",
    how: "Offer simple choices (e.g. show two outfits). Document Best Interest decisions when capacity is absent.",
    good: "Offering a choice of two breakfast plates visually, allowing resident to point.",
    poor: "Carers deciding everything for the resident without offering choice, violating MCA.",
    when: "Escalate if capacity changes or if formal MCA assessments are overdue.",
    who: "Inform the Registered Manager, Social Worker, and family/LPA.",
    record: "Record MCA assessments, Best Interest decisions, and daily choice logs.",
    dignity: "Respects the resident's right to make choices and control their life.",
    success: "Resident makes choices daily, or care aligns with documented Best Interests.",
    evidence: "Completed MCA assessments, Best Interest documents, and choice logs."
  },
  confusion: {
    title: "Confusion",
    why: "Reduces terror and distress associated with cognitive disorientation.",
    how: "Provide calm reassurance. Use familiar objects (memory box) to ground the resident.",
    good: "Sitting with Arthur, looking at his family album, and talking about his favorite topics.",
    poor: "Leaving a confused resident alone, or arguing about facts.",
    when: "Escalate if confusion is sudden (possible UTI or delirium indicator).",
    who: "Inform the Duty Nurse and GP (for urine test).",
    record: "Record onset of confusion, triggers, and reassurance techniques used.",
    dignity: "Provides comfort and safety during disorienting moments.",
    success: "Resident settles and feels secure after reassurance.",
    evidence: "Urinalysis logs, care logs, and review notes."
  },
  nightBehaviour: {
    title: "Night-time behaviour",
    why: "Ensures sleep quality and prevents night-time falls or exit-seeking.",
    how: "Conduct quiet checks. Ensure pathways are clear. Offer toilet support if awake.",
    good: "Arthur wanders into the corridor; night staff offer a warm drink and guide him back to bed.",
    poor: "Shouting at a resident to 'go back to bed,' causing fear and agitation.",
    when: "Escalate if night wandering increases, causing falls or high fatigue.",
    who: "Inform the GP (sleep study/med review) and Care Manager.",
    record: "Record sleep logs, wandering times, interventions, and mood.",
    dignity: "Maintains a safe, caring, and unhurried response at night.",
    success: "Resident settles back to sleep comfortably.",
    evidence: "Night-time logs and falls risk reviews."
  },
  sundowning: {
    title: "Sundowning",
    why: "Late afternoon agitation is common in dementia. Proactive care prevents escalation.",
    how: "Draw curtains, turn on warm lighting at 15:30. Engage in soothing activity (music).",
    good: "Pre-empting evening agitation by inviting Arthur to listen to classical music at 16:00.",
    poor: "Ignoring late afternoon distress until the resident is highly agitated.",
    when: "Escalate if sundowning behaviors pose safety risks to self or others.",
    who: "Inform the GP (medication review) and Dementia Lead.",
    record: "Record timing of sundowning, triggers, calming methods, and outcomes.",
    dignity: "Protects comfort by managing environmental triggers before distress peaks.",
    success: "Resident remains relaxed and settled during the late afternoon shift transition.",
    evidence: "Sundowning logs and care plan adjustments."
  },
  distress: {
    title: "Distress",
    why: "Soothes frightening hallucinations or delusions, keeping the resident safe.",
    how: "Do NOT argue with hallucinations. Say: 'I can see you are worried, you are safe here.'",
    good: "Arthur sees people in the garden. Carer says: 'I will make sure the doors are locked, you are safe here.'",
    poor: "Telling the resident: 'You are crazy, there is no one there,' breaking trust.",
    when: "Escalate if hallucinations cause extreme panic or aggressive behaviors.",
    who: "Inform the Psychiatrist, GP, and Registered Manager.",
    record: "Record hallucination details, level of fear, calming methods, and medication.",
    dignity: "Validates fear and provides comforting security without judgment.",
    success: "Resident relaxes and returns to reality after calm reassurance.",
    evidence: "Incident logs, psychiatric reports, and calming protocol documents."
  },
  repetitiveQuestions: {
    title: "Repetitive questions",
    why: "Answers anxiety rather than repeating facts, restoring peace of mind.",
    how: "Answer with validation therapy. Use whiteboards or note cards showing the answer.",
    good: "Arthur asks when lunch is. Carer says: 'Lunch is at 12:30. Let's look at this photo book.'",
    poor: "Replying: 'I just told you 5 minutes ago!' causing frustration.",
    when: "Escalate if repetitive questioning turns into deep distress.",
    who: "Inform the Team Leader and GP.",
    record: "Record questions asked, effective responses, and anxiety levels.",
    dignity: "Answers with infinite patience, validating the resident's worry.",
    success: "Resident settled after answer and directed to an activity.",
    evidence: "Behavior logs and staff training folders."
  },
  lifeStory: {
    title: "Life story",
    why: "Keeps the resident's identity alive and provides conversational hooks.",
    how: "Use the resident's Life Story Book during 1-to-1 care sessions.",
    good: "Looking at photos of Arthur's time in the Navy, which triggers happy memories.",
    poor: "Treating the resident as a set of medical needs, ignoring their past.",
    when: "Escalate if resident shows no response or withdraws from life story talks.",
    who: "Inform the Activities team and family.",
    record: "Record life story topics discussed, memories shared, and engagement level.",
    dignity: "Celebrates the resident's history and achievements.",
    success: "Resident actively shares stories and feels valued.",
    evidence: "Completed Life Story Book and activities records."
  },
  familyHistory: {
    title: "Family history",
    why: "Maintains connection with loved ones and guides staff on key contacts.",
    how: "Keep a list of family names and relationships. Refer to them during conversations.",
    good: "Talking to Arthur about his daughter Sonya, using her name to soothe him.",
    poor: "Referring to family members generically as 'your visitor' or 'your daughter' without names.",
    when: "Escalate if family visits cause distress or if conflict arises.",
    who: "Inform the Registered Manager and Social Worker.",
    record: "Record family names, visits, phone calls, and resident's reaction.",
    dignity: "Respects family relationships and personal connections.",
    success: "Resident feels connected to family and looks forward to visits.",
    evidence: "Family contact sheets and communication records."
  },
  favouriteTopics: {
    title: "Favourite topics",
    why: "Promotes joy, reduces boredom, and supports meaningful engagement.",
    how: "Engage in hobbies like gardening, painting, or discussing favorite topics (Navy).",
    good: "Setting up a raised garden bed for Arthur so he can plant flowers safely.",
    poor: "Leaving the resident seated in front of a TV all day with no activity.",
    when: "Escalate if resident loses interest in all activities.",
    who: "Inform the Activities Lead and GP.",
    record: "Record activities joined, level of engagement, and mood.",
    dignity: "Honors the resident's interests and supports their right to a full life.",
    success: "Resident participates in activities and shows positive mood.",
    evidence: "Activities logs, resident feedback, and photographs."
  },
  sensorySupport: {
    title: "Sensory support",
    why: "Stimulates senses and provides comfort, especially in later stages.",
    how: "Use soft music (Navy band), aromatherapy, or tactile objects (fidget blanket).",
    good: "Playing Arthur's favorite classical music during bath time to reduce anxiety.",
    poor: "Leaving resident in a loud, over-stimulating environment.",
    when: "Escalate if sensory aids cause agitation or distress.",
    who: "Inform the Activities team and GP.",
    record: "Record sensory tools used, resident's response, and duration.",
    dignity: "Provides gentle comfort that matches the resident's sensory needs.",
    success: "Resident is relaxed and shows signs of comfort.",
    evidence: "Sensory log sheets and care notes."
  },
  environment: {
    title: "Environment",
    why: "Prevents disorientation and falls caused by shadows or poor lighting.",
    how: "Ensure rooms are brightly lit during the day. Use low-level night lights.",
    good: "Drawing curtains and turning on warm lighting at 16:00 to reduce sundowning.",
    poor: "Leaving the resident in a dark room with shadows, causing fear.",
    when: "Escalate if environmental factors cause falls or distress.",
    who: "Inform the Maintenance Officer and Team Leader.",
    record: "Record environmental adjustments made and outcomes.",
    dignity: "Creates a safe, comforting space that supports orientation.",
    success: "Resident navigates their room safely with no exit-seeking.",
    evidence: "Environmental risk assessments and logs."
  },
  sleepHydration: {
    title: "Sleep, Hydration & Nutrition",
    why: "Dementia increases the risk of dehydration and weight loss. Monitoring is vital.",
    how: "Offer drinks in colored cups. Serve finger foods. Log all food and fluid intake.",
    good: "Arthur drinks more water when served in a red cup; food intake is 90% (finger food).",
    poor: "Leaving a hot drink out of reach, or ignoring low fluid intake.",
    when: "Escalate if fluid intake falls below 1000ml in 24 hours.",
    who: "Inform the Dietitian, SALT Team, and GP.",
    record: "Record food and fluid logs, weight checks, and help needed.",
    dignity: "Supports independent eating with finger foods and colored cups.",
    success: "Resident maintains their weight and remains hydrated.",
    evidence: "Food and fluid charts, weight logs, and dietitian reviews."
  },
  medicationSafeguarding: {
    title: "Medication & Safeguarding",
    why: "Ensures legal compliance for restrictive practices (DoLS) and medication.",
    how: "Check DoLS status. Administer meds as prescribed. Log any refusals.",
    good: "Administering medication in line with the active DoLS authorization.",
    poor: "Giving covert medication without a formal Best Interest decision.",
    when: "Escalate immediately if resident repeatedly refuses medication.",
    who: "Inform the GP, Registered Manager, and Safeguarding Team.",
    record: "Record medication given, refusals, and DoLS status.",
    dignity: "Ensures legal compliance and protects resident rights.",
    success: "Medication is taken safely and DoLS status is active and reviewed.",
    evidence: "MAR charts, DoLS certificates, and Best Interest logs."
  },
  staffSayings: {
    title: "Dementia Communication Guide",
    why: "Ensures all staff use consistent, validating language to build trust.",
    how: "Read the communication guide before starting care. Use validating phrases.",
    good: "Staff say: 'You are safe here, let me help you,' when Arthur is anxious.",
    poor: "Staff say: 'Stop shouting, you are in a care home,' breaking trust.",
    when: "Escalate if staff use inappropriate or confrontational language.",
    who: "Inform the Registered Manager and Team Leader.",
    record: "Record resident responses to validating communication.",
    dignity: "Maintains a respectful, validating environment for the resident.",
    success: "Resident feels safe and respected, with minimal agitation.",
    evidence: "Staff training records and observation audits."
  }
};
